# 1. Data in NumPy

## Introducing NumPy

Python is convenient, but it can also be slow. However, it does allow you to access libraries that execute faster code written in languages like C. NumPy is one such library: it provides fast alternatives to math operations in Python and is designed to work efficiently with groups of numbers - like matrices.

### Importing NumPy

In [2]:
import numpy as np

### Data Types and Shapes

The most common way to work with numbers in NumPy is through `ndarray` objects. They are similar to Python lists, but can have any number of dimensions. Also, ndarray supports fast math operations, which is just what we want.

Since it can store any number of dimensions, you can use `ndarray`s to represent any data types we covered before: scalars, vectors, matrices, or tensors.

### Scalars

Scalars in NumPy are a bit more involved than in Python. Instead of Python's basic types like `int`, `float`, etc., NumPy lets you specify signed and unsigned types, as well as different sizes. So instead of Python's `int`, you have access to types like `uint8`, `int8`, `uint16`, `int16`, and so on.

These types are important because every object you make (vectors, matrices, tensors) eventually stores scalars. And when you create a NumPy array, you can specify the type - but **every item in the array must have the same type**. In this regard, NumPy arrays are more like C arrays than Python lists.

If you want to create a NumPy array that holds a scalar, you do so by passing the value to NumPy's `array` function, like so:

In [3]:
s = np.array(5)
s

array(5)

You can still perform math between `ndarray`s, NumPy scalars, and normal Python scalars, though, as you'll see in the element-wise math lesson.

You can see the shape of your arrays by checking their `shape` attribute. So if you executed this code:

In [4]:
s.shape

()

It would print out the result, an empty pair of parenthesis, `()`. This indicates that it has zero dimensions.

Even though scalars are inside arrays, you still use them like a normal scalar. So you could type:

In [6]:
x = s + 3
x

8

and `x` would now equal `8`. If you were to check the type of `x`, you'd find it probably `numpy.int64`, because its working with NumPy types, not Python types.

By the way, even scalar types support most of the array functions. so you can call `x.shape` and it would return `()` because it has zero dimensions, even though it is not an array. If you tried that with a normal Python scalar, you'd get an error.

### Vectors

To create a vector, you'd pass a Python list to the `array` function, like this:

In [7]:
v = np.array([1,2,3])
v

array([1, 2, 3])

If you check a vector's `shape` attribute, it will return a single number representing the vector's one-dimensional length. In the above example, `v.shape` would return `(3,)`

Now that there is a number, you can see that the shape is a tuple with the sizes of each of the `ndarray`'s dimensions. For scalars it was just an empty tuple, but vectors have one dimensions, so the tuple includes a number and a comma. (Python doesn't understand `(3)` as a tuple with one item, so it requires the comma.

You can access an element within the vector using indices, like this

In [8]:
x = v[1]
x

2

NumPy also supports advanced indexing techniques. For example, to access the items from the second element onward, you would say:

In [9]:
v[1:]

array([2, 3])

NumPy slicing is quite powerful, allowing you to access any combination of items in an `ndarray`.

### Matrices

You create matrices using NumPy's `array` function, just you did for vectors. However, instead of just passing in a list, you need to supply a list of lists, where each list represents a row. So to create a 3x3 matrix containing the numbers one through nine, you could do this:

In [14]:
m = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])
m

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [15]:
m.shape

(3, 3)

In [16]:
m[1][2]

6

### Tensors

Tensors are just like vectors and matrices, but they can have more dimensions. For example, to create 3x3x2x1 tensor, you could do the following:

In [17]:
t = np.array([
    [
        [
            [1],[2]
        ],[
            [3],[4]
        ],[
            [5],[6]
        ]
    ],[
        [
            [7],[8]
        ],[
            [9],[10]
        ],[
            [11],[12]
        ]
    ],[
        [
            [13],[14]
        ],[
            [15],[16]
        ],[
            [17],[17]
        ]
    ]
])
t

array([[[[ 1],
         [ 2]],

        [[ 3],
         [ 4]],

        [[ 5],
         [ 6]]],


       [[[ 7],
         [ 8]],

        [[ 9],
         [10]],

        [[11],
         [12]]],


       [[[13],
         [14]],

        [[15],
         [16]],

        [[17],
         [17]]]])

In [18]:
t.shape

(3, 3, 2, 1)

In [19]:
t[2][1][1][0]

16

### Changing Shapes

Sometimes you'll need to change the shape of your data without actually changing its contents. For example, you may have a vector, which is one-dimensional, but need a matrix, which is two-dimensional. There are two ways you can do that.

Let's say you have the following vector:

In [21]:
v = np.array([1,2,3,4])
v

array([1, 2, 3, 4])

In [22]:
v.shape

(4,)

But what if you want a 1x4 matrix? You can accomplish that with`reshape` function, like so:

In [23]:
x = v.reshape(4,1)
x

array([[1],
       [2],
       [3],
       [4]])

`reshape` function works for more than just adding a dimension of size 1.

One more thing about reshaping NumPy arrays: If you see code from experienced NumPy users, you will often see them use a special slicing syntax instead of calling `reshape`. Using this syntax, the previous two examples would look like this:

In [26]:
x1 = v[None, :]
x1

array([[1, 2, 3, 4]])

In [27]:
x2 = v[:, None]
x2

array([[1],
       [2],
       [3],
       [4]])

Those lines create a slice that looks at all of the items of `v` but asks NumPy to add a new dimension of size 1 for the associated axis.

# 2. Element-wise Matrix Operations in NumPy

## The Python way

Suppose you had a list of numbers, and you wanted add `5` to every itme in the list. Without NumPy, you might do something like this:

In [29]:
values = [1,2,3,4,5]
for i in range(len(values)):
    values[i] += 5
values

[6, 7, 8, 9, 10]

## The NumPy way

In NumPy, we could do the following:

In [31]:
values = [1,2,3,4,5]
values = np.array(values) + 5
values

array([ 6,  7,  8,  9, 10])

Creating that array may seem odd, but normally you'll be storing your data in `ndarray`s anyway. So if you already had an `ndaaray` named `values`, you could have done:

In [33]:
values += 5
values

array([16, 17, 18, 19, 20])

We should point out, NumPy actually has functions for things like adding, multiplying, etc. But it also supports using the standard math operators. So the following two lines are equivalent:

In [36]:
some_array_1 = [1,2,3,4,5]
some_array_2 = [1,2,3,4,5]
x1 = np.multiply(some_array_1, 5)
x2 = some_array_2 * 5
x1

array([ 5, 10, 15, 20, 25])

In [37]:
x2

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5]

We will usually use the operators instead of the functions because they are more convenient to type and easier to read, but it's really just personal preference.

One more example of operating with scalars and `ndarrays`. Let's say you have a matrix `m` and you want to reuse it, but first you need to set all its values to zero. Easy, just multiply by zero and assign the result back to the matrix, like this:

In [39]:
m = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])
m

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [40]:
m *= 0
m

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

### Element-wise Matrix Operations

The same functions and operators that work with scalars and matrices also work with other dimensions. You just need to make sure that the items you perform the operation on have compatible shapes.

Let's say you want to get the squared values of a matrix. That's simply `x *= m`.

This works because it's an element-wise multiplication between two identically-shaped matrices. Here's the example from the video:

In [41]:
a = np.array([
    [1,3],
    [5,7]
])
a

array([[1, 3],
       [5, 7]])

In [42]:
b = np.array([
    [2,4],
    [6,8]
])
b

array([[2, 4],
       [6, 8]])

In [43]:
a + b

array([[ 3,  7],
       [11, 15]])

And if you try working with incompatible shapes, like the other example from the video, you'd get an error:

In [44]:
c = np.array([
    [2,3,6],
    [4,5,9],
    [1,8,7]
])
c

array([[2, 3, 6],
       [4, 5, 9],
       [1, 8, 7]])

In [45]:
a.shape

(2, 2)

In [46]:
c.shape

(3, 3)

In [47]:
a + c

ValueError: operands could not be broadcast together with shapes (2,2) (3,3) 

# 3. Matrix Multiplication

## Important Reminders About Matrix multiplication

* The **number** of **columns** in the **left** matrix **must equal** the **number** of **rows** in the **right** matrix.

* The **answer** matrix **always has** the **same number** of **rows** as the **left** matrix and the **same number** of **columns** as the **right** matrix.

* **Order matters**. Multiplying **A * B** is **not the same** as multiplying **B * A**

* Data in the **left** matrix **should be** arranged as **rows**., while data in the **right** matrix **should be** arranged as **columns**.

## NumPy Matrix Multiplication

### Element-wise Multiplication

Revisiting element-wise multiplication.

In [48]:
m = np.array([
    [1,2,3],
    [4,5,6]
])
m

array([[1, 2, 3],
       [4, 5, 6]])

In [49]:
n = m * 0.25
n

array([[0.25, 0.5 , 0.75],
       [1.  , 1.25, 1.5 ]])

In [50]:
m * n

array([[0.25, 1.  , 2.25],
       [4.  , 6.25, 9.  ]])

In [51]:
np.multiply(m, n)

array([[0.25, 1.  , 2.25],
       [4.  , 6.25, 9.  ]])

### Matrix Product

To find the matrix product, you use NumPy's `matmul` function.

If you have compatible shapes, then it's as simple as this:

In [53]:
a = np.array([
    [1,2,3,4],
    [5,6,7,8]
])
a

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [54]:
a.shape

(2, 4)

In [56]:
b = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9],
    [10,11,12]
])
b

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [57]:
b.shape

(4, 3)

In [59]:
c = np.matmul(a,b)
c

array([[ 70,  80,  90],
       [158, 184, 210]])

In [60]:
c.shape

(2, 3)

### NumPy's `dot` function

You can use `dot` function for two dimensional matrix multiplication just as `matmul`. Like following:

In [61]:
a = np.array([
    [1,2],
    [3,4]
])
a

array([[1, 2],
       [3, 4]])

In [62]:
np.dot(a,a)

array([[ 7, 10],
       [15, 22]])

In [63]:
a.dot(a)

array([[ 7, 10],
       [15, 22]])

In [64]:
np.matmul(a,a)

array([[ 7, 10],
       [15, 22]])

# 4. Matrix Transposes

## Transpose

Getting the transpose of a matrix is really easy in NumPy. Simply access its `T` attribute. There is also a `transpose()` function which returns the same thing, but you'll rarely see that used because typing `T` is so much easier :)

For example:

In [66]:
m = np.array([
    [1,2,3,4],
    [5,6,7,8],
    [9,10,11,12]
])
m

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [67]:
m.T

array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])

NumPy does this without actually moving any data in memory - it simply changes the way it indexes the original matrix - so it's quite efficient.

However, that also means you need to be careful with how you modify objects, because **they are sharing the same data**. For example, with the same matrix `m` from above, let's make a new variable `m_t` that stores `m` transpose. Then look what happens if we modifiy a value in `m_t`:

In [68]:
m_t = m.T
m_t

array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])

In [70]:
m_t[3][1] = 200
m_t

array([[  1,   5,   9],
       [  2,   6,  10],
       [  3,   7,  11],
       [  4, 200,  12]])

In [71]:
m

array([[  1,   2,   3,   4],
       [  5,   6,   7, 200],
       [  9,  10,  11,  12]])

## A real use case

There is one place you'll almost certainly end up using a transpose. Let's say you have the following two matrices, called `inputs` and `weights`.

In [72]:
inputs = np.array([
    [-0.27, 0.45, 0.64, 0.31]
])
inputs

array([[-0.27,  0.45,  0.64,  0.31]])

In [73]:
inputs.shape

(1, 4)

In [75]:
weights = np.array([
    [0.02, 0.001, -0.03, 0.036], 
    [0.04, -0.003, 0.025, 0.009], 
    [0.012, -0.045, 0.28, -0.067]
])
weights

array([[ 0.02 ,  0.001, -0.03 ,  0.036],
       [ 0.04 , -0.003,  0.025,  0.009],
       [ 0.012, -0.045,  0.28 , -0.067]])

In [76]:
weights.shape

(3, 4)

Trying to find out `matrix product` of inputs and weights will throw error.

In [78]:
np.matmul(inputs, weights)

ValueError: shapes (1,4) and (3,4) not aligned: 4 (dim 1) != 3 (dim 0)

But it will work if we use transpose properly.

In [79]:
np.matmul(inputs, weights.T)

array([[-0.01299,  0.00664,  0.13494]])

swapping order also works

In [80]:
np.matmul(weights, inputs.T)

array([[-0.01299],
       [ 0.00664],
       [ 0.13494]])